version: 2.1

environment: &environment
  LOG_LEVEL: WARN

jobs:
  functional_tests:
    working_directory: ~/repos/ping

    docker:
      - image: circleci/ruby:2.6-jessie-node
        environment:
          <<: *environment

    steps:
      - checkout

      - restore_cache:
          keys:
            - ping-bundle-v2-{{ checksum "Gemfile.lock" }}
            - ping-bundle-v2-

      - run:
          name: Which bundler?
          command: bundle -v

      - save_cache:
          keys:
            - ping-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: run_functional_test
          command: bundle exec rake test

      - store_test_results:
          path: test_results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_functional_test
