version: 2.1

environment: &environment
  LOG_LEVEL: WARN

jobs:
  functional_tests:
    working_directory: ~/repos/ping

    docker:
      - image: circleci/ruby:2.6.4-buster-node
        environment:
          <<: *environment

    steps:
      - checkout

      - run:
        name: check dependencies
        command: |
          bundle -v
          bundle exec ruby -v

      - restore_cache:
          keys:
            - ping-bundle-v2-{{ checksum "Gemfile.lock" }}
            - ping-bundle-v2-

      - save_cache:
          keys:
            - ping-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: run_functional_test
          command: bundle exec rake test

      - store_test_results:
          path: test_results

workflows:
  version: 2
  build_and_test:
    jobs:
      - functional_tests
