version: 2.1

environment: &environment
  LOG_LEVEL: WARN

jobs:
  functional_tests:
    working_directory: ~/repos/ping

    docker:
      - image: circleci/ruby:2.6.4-buster-node
        environment:
          <<: *environment

    steps:
      - checkout

      - run:
          name: check dependencies
          command: |
            bundle -v
            bundle exec ruby -v

      - restore_cache:
          keys:
            - ping-bundle-v2-{{ checksum "ping.gemspec" }}
            - ping-bundle-v2-

      - run:
          name: install gems
          command: bundle install && bundle clean

      - save_cache:
          key: ping-bundle-v2-{{ checksum "ping.gemspec" }}
          paths:
            - vendor/bundle

      - run:
          name: run functional tests
          command: bundle exec rake test

      - store_test_results:
          path: test_results

  publish_to_rubygems:
    working_directory: ~/repos/ping

    docker:
      - image: circleci/ruby:2.6.4-buster-node
        environment:
          <<: *environment

    steps:
      - checkout

      - run:
          name: setup Rubygems
          command: bash .circleci/setup-rubygems.sh

      - run:
          name: publish to Rubygems
          command: |
            gem build ping.gemspec
            gem push "ping-$(git describe --tags).gem"

workflows:
  version: 2
  build_and_test:
    jobs:
      - functional_tests
      - publish_to_rubygems:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
